name: Linux CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build-linux:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: true

      matrix:
        build_type: [Release, Debug]
        c_compiler: [gcc-14, clang-18]
        include:
          - c_compiler: gcc-14
            cpp_compiler: g++-14
          - c_compiler: clang-18
            cpp_compiler: clang++-18

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Install system dependencies
      run: >
        sudo add-apt-repository universe ;
        sudo apt update ;
        sudo apt install g++-14 gcc-14 ;
        wget https://apt.llvm.org/llvm.sh ;
        chmod u+x llvm.sh ;
        sudo ./llvm.sh 18

    - name: Install conan
      run: >
        python3 -m venv ${{ github.workspace }}/.venv ;
        source ${{ github.workspace }}/.venv/bin/activate ;
        pip install conan==2.14.0 ;
        conan profile detect

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: >
        echo "home=$HOME" >> "$GITHUB_OUTPUT" ;
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Cache conan dependencies
      id: cache-conan
      uses: actions/cache@v4.2.0
      env:
        cache-name: cache-conan
      with:
        path: ${{ steps.strings.outputs.home }}/.conan2
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.build_type }}-${{ matrix.c_compiler }}-${{ hashFiles('CMakeLists.txt') }}--${{ hashFiles('conanfile.txt') }}

    - name: Configure CMake
      run: >
        export LLVM_DIR=/usr/lib/llvm-18/ ;
        source ${{ github.workspace }}/.venv/bin/activate ;
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DRUNNER=1
        -S ${{ github.workspace }}

    - name: Build
      run: >
        source ${{ github.workspace }}/.venv/bin/activate ;
        cmake --build ${{ steps.strings.outputs.build-output-dir }} --parallel 4
        --config ${{ matrix.build_type }}

    - name: Test
      run: >
        source ${{ github.workspace }}/.venv/bin/activate ;
        ctest --test-dir ${{ steps.strings.outputs.build-output-dir }}
        --build-config ${{ matrix.build_type }} 
        --output-on-failure
