name: Windows CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build-windows:
    runs-on: windows-2022

    strategy:
      # TODO: Set to true once Windows building works well.
      fail-fast: false

      matrix:
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v4.2.2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Install conan
      run: >
        python3 -m venv ${{ github.workspace }}\.venv ;
        cd ${{ github.workspace }} ;
        .\.venv\Scripts\activate ;
        pip install conan==2.14.0 ;
        conan profile detect

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      run: >
        echo "home=$HOME" >> $env:GITHUB_OUTPUT ;
        echo "build-output-dir=${{ github.workspace }}\build" >> $env:GITHUB_OUTPUT ;
        echo "build-type-lower=${{ matrix.build_type }}".ToLower() >> $env:GITHUB_OUTPUT

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v4.2.0
      env:
        cache-name: cache-conan
      with:
        path: |
          ${{ steps.strings.outputs.home }}/.conan2
          ${{ steps.strings.outputs.home }}/llvm
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.build_type }}--${{ hashFiles('CMakeLists.txt') }}--${{ hashFiles('conanfile.txt') }}

    - if: ${{ steps.cache-dependencies.outputs.cache-hit == 'true' }}
      name: Remove conan system-reqs cache and delete boost conan_sources.tgz
      continue-on-error: true
      run: >
        cd ${{ github.workspace }} ;
        .\.venv\Scripts\activate ;
        conan remove --system-reqs '*' ;
        Get-ChildItem ${{ steps.strings.outputs.home }}\.conan2\data\boost
        -File -Include conan_sources.tgz -Recurse -Force
        | Remove-Item -Recurse -Force

    - name: Install LLVM
      run: >
        .\setup_llvm.ps1 /${{ matrix.build_type }} /Force /Jobs:4

    - name: Configure CMake
      run: >
        cd ${{ github.workspace }} ;
        .\.venv\Scripts\activate ;
        $env:PATH="${{ steps.strings.outputs.home }}/llvm/${{ steps.strings.outputs.build-type-lower }}/bin;"+$env:PATH ;
        $env:PATH="${{ steps.strings.outputs.home }}/llvm/${{ steps.strings.outputs.build-type-lower }}/lib;"+$env:PATH ;
        $env:LLVM_DIR="${{ steps.strings.outputs.home }}/llvm/${{ steps.strings.outputs.build-type-lower }}" ;
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=cl
        -DCMAKE_C_COMPILER=cl
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DRUNNER=1
        -S ${{ github.workspace }}

    - name: Build
      run: >
        cd ${{ github.workspace }} ;
        .\.venv\Scripts\activate ;
        $env:PATH="${{ steps.strings.outputs.home }}/llvm/${{ steps.strings.outputs.build-type-lower }}/bin;"+$env:PATH ;
        $env:PATH="${{ steps.strings.outputs.home }}/llvm/${{ steps.strings.outputs.build-type-lower }}/lib;"+$env:PATH ;
        $env:LLVM_DIR="LLVM_DIR="${{ steps.strings.outputs.home }}/llvm/${{ steps.strings.outputs.build-type-lower }}" ;
        cmake --build ${{ steps.strings.outputs.build-output-dir }} --parallel 4
        --config ${{ matrix.build_type }}

    - name: Test
      run: >
        cd ${{ github.workspace }} ;
        .\.venv\Scripts\activate ;
        ctest --test-dir ${{ steps.strings.outputs.build-output-dir }}
        --build-config ${{ matrix.build_type }} 
        --output-on-failure
